version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/frontend  # Mount the frontend directory

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./backend:/backend  # Mount the backend directory
